"""remove_transaction_id_column

Revision ID: 553905fca6db
Revises: 00d1d3968ec2
Create Date: 2026-02-16 15:11:05.737074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553905fca6db'
down_revision: Union[str, Sequence[str], None] = '00d1d3968ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_id', sa.String(), nullable=True))
    # ### end Alembic commands ###
